---
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

name: testproject
description: A test project

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  recharge: ^0.1.0
